const LOGIN = {
	IN_PROGRESS: 'LOGIN.IN_PROGRESS',
	ERROR: 'LOGIN.ERROR',
	SUCCESS: 'LOGIN.SUCCESS',
	LOGOUT: 'LOGIN.LOGOUT'
}

const SIGNUP = {
	IN_PROGRESS: 'SIGNUP.IN_PROGRESS',
	ERROR: 'SIGNUP.ERROR',
	SUCCESS: 'SIGNUP.SUCCESS'
}

const CLASSES = {
	LOADING: 'CLASSES_LOADING',
	ADDED: 'CLASSES_ADDED',
	REMOVED: 'CLASSES_REMOVED',
	UPDATED: 'CLASSES_UPDATED',
	ERROR: 'CLASSES_ERROR',
	SELECT: 'SELECT_CLASS',
	UNSELECT: 'UNSELECT_CLASS'
}

export default {
	LOGIN, SIGNUP, CLASSES
}