const LOGIN = {
	IN_PROGRESS: 'LOGIN.IN_PROGRESS',
	ERROR: 'LOGIN.ERROR',
	SUCCESS: 'LOGIN.SUCCESS',
	LOGOUT: 'LOGIN.LOGOUT'
}

const SIGNUP = {
	IN_PROGRESS: 'SIGNUP.IN_PROGRESS',
	ERROR: 'SIGNUP.ERROR',
	SUCCESS: 'SIGNUP.SUCCESS'
}

export default {
	LOGIN, SIGNUP
}